"""
Renders test/input_html.html for one board (substituting {{TOKENS}} from that board's
<NAME>/board.json, a sibling of this firmware/ directory), gzip-compresses it, and writes
it as a C byte array to include/components/WebServer/page_index.h.

Used two ways:
  - Automatically, as part of boards/generate_board_config.py (itself run by PlatformIO's
    `extra_scripts` pre-build hook) - so every `pio run -e <board>` regenerates the right
    page_index.h before compiling, from the single input_html.html template.
  - Standalone, for local preview/debugging:
        python3 test/converter.py <board_name>
"""
import gzip
import json
import os
import sys


def render_template(template_text, cfg):
    led = cfg.get("led", {})
    tokens = {
        "WHITE_LABEL": led.get("white_label", "White:"),
        "WHITE_NOTICE": led.get("white_notice", ""),
        "DISABLED_NOTICE": led.get(
            "disabled_notice",
            "Light color settings are not supported on this board yet.",
        ),
        "LED_CONTROL_ENABLED": "1" if led.get("led_control_enabled") else "0",
        "ANIMATIONS_DISPLAY": "" if led.get("animations", {}).get("enabled") else "none",
    }
    rendered = template_text
    for name, value in tokens.items():
        rendered = rendered.replace("{{" + name + "}}", value)
    return rendered


def compress_to_static_array(html_bytes):
    compressed = gzip.compress(html_bytes)
    lines = [
        "#ifndef HTML_CONTENT_H",
        "#define HTML_CONTENT_H",
        "",
        "// AUTO-GENERATED by test/converter.py from test/input_html.html - do not hand-edit.",
        "// Size of the HTML content in bytes",
        "const unsigned int HTML_CONTENT_SIZE = {};".format(len(compressed)),
        "",
        "// HTML content in bytes (compressed)",
        "const unsigned char HTML_CONTENT[] = {",
    ]
    row = []
    for byte in compressed:
        row.append("0x{:02X},".format(byte))
        if len(row) == 20:
            lines.append("  " + "".join(row))
            row = []
    if row:
        lines.append("  " + "".join(row))
    lines += ["};", "", "#endif // HTML_CONTENT_H", ""]
    return "\n".join(lines)


def generate_page_index(cfg, firmware_root):
    template_path = os.path.join(firmware_root, "test", "input_html.html")
    output_header_path = os.path.join(firmware_root, "include", "components", "WebServer", "page_index.h")

    with open(template_path, "rb") as f:
        template_text = f.read().decode("utf-8")
    rendered = render_template(template_text, cfg)
    header = compress_to_static_array(rendered.encode("utf-8"))
    os.makedirs(os.path.dirname(output_header_path), exist_ok=True)
    with open(output_header_path, "w") as f:
        f.write(header)
    print("[converter] {}: wrote {} ({} bytes source, {} bytes compressed)".format(
        cfg["name"], output_header_path, len(rendered), len(gzip.compress(rendered.encode("utf-8")))
    ))


if __name__ == "__main__":
    if len(sys.argv) < 2:
        sys.exit("usage: converter.py <board_name>")
    firmware_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    repo_root = os.path.dirname(firmware_root)
    board_path = os.path.join(repo_root, sys.argv[1].upper(), "board.json")
    with open(board_path) as f:
        board_cfg = json.load(f)
    generate_page_index(board_cfg, firmware_root)
