#!/usr/bin/env python3
"""
Generates include/generated/board_config.h from <NAME>/board.json (top-level, a sibling
of firmware/ - e.g. ../OREIN/board.json for the "orein" env) plus firmware/app_config.json
for settings shared across every bulb (AP credentials, OTA firmware URL).

Run automatically as a PlatformIO pre-build script (see platformio.ini's
`extra_scripts = pre:boards/generate_board_config.py`), which passes the
PlatformIO environment name in via env["PIOENV"] so each `pio run -e
<board>` regenerates the header for the right board before compiling.
`<board>` maps to a folder via `<board>.upper()` (e.g. "orein" -> "OREIN/").

Can also be run standalone for local inspection/debugging:
    python3 boards/generate_board_config.py <board_name>
"""
import json
import os
import sys


def load_app_config(firmware_root):
    path = os.path.join(firmware_root, "app_config.json")
    with open(path) as f:
        return json.load(f)


def load_board(repo_root, board_name):
    path = os.path.join(repo_root, board_name.upper(), "board.json")
    with open(path) as f:
        return json.load(f)


def generate_header(cfg, app_cfg):
    led = cfg.get("led", {})
    driver = led.get("driver", "none")
    driver_macro = {
        "none": "LED_DRIVER_NONE",
        "pwm_direct": "LED_DRIVER_PWM_DIRECT",
        "bus": "LED_DRIVER_BUS",
    }[driver]

    pwm_direct = led.get("pwm_direct", {})
    bus = led.get("bus", {})
    # Animations only exist for the bus driver today (system_manager.cpp's tick logic
    # writes bus channels directly) - force off for any other driver regardless of what
    # board.json says, so callers only need to check this one macro, not this + driver.
    animations_enabled = led.get("animations", {}).get("enabled", False) and driver == "bus"

    white_channels = pwm_direct.get("white_channels", bus.get("white_channels", 0))

    # channel_order: which logical channel (R/G/B) feeds the bus's R-slot/G-slot/B-slot,
    # read left to right - "RGB" (default, no swap) or e.g. OREIN's confirmed "BGR". This
    # replaces the old boolean swap_red_blue with something that generalizes to any of the
    # 6 R/G/B permutations, not just a single red<->blue swap, should a future board need
    # one. Resolved here into 3 slot-source indices (0=R,1=G,2=B) so system_manager.cpp can
    # do a plain array lookup instead of per-permutation #if/#elif branches.
    channel_order = bus.get("channel_order", "RGB").upper()
    role_index = {"R": 0, "G": 1, "B": 2}
    if sorted(channel_order) != ["B", "G", "R"]:
        sys.exit(
            "{}: bus.channel_order must be a permutation of R/G/B, got {!r}".format(
                cfg["name"], channel_order
            )
        )
    r_slot_source, g_slot_source, b_slot_source = (role_index[c] for c in channel_order)

    ap_ssid = cfg.get("ap_ssid", app_cfg["ap_ssid"])
    ap_password = cfg.get("ap_password", app_cfg["ap_password"])
    ap_hidden = cfg.get("ap_hidden", app_cfg.get("ap_hidden", False))
    # No working default exists - the original project's EC2 host no longer serves
    # firmware. Blank unless a board.json or app_config.json sets one; the /update
    # handler refuses to run with a blank URL rather than fetching from nothing.
    ota_firmware_url = cfg.get("ota_firmware_url", app_cfg.get("ota_firmware_url", ""))

    lines = [
        "#pragma once",
        "// AUTO-GENERATED by boards/generate_board_config.py from {}/board.json".format(cfg["name"]),
        "// (+ firmware/app_config.json for AP defaults). Do not hand-edit - edit those and rebuild instead.",
        "",
        '#define BOARD_NAME "{}"'.format(cfg["name"]),
        '#define BOARD_DISPLAY_NAME "{}"'.format(cfg["display_name"]),
        '#define BOARD_AP_SSID "{}"'.format(ap_ssid),
        '#define BOARD_AP_PASSWORD "{}"'.format(ap_password),
        "#define BOARD_AP_HIDDEN {}".format(1 if ap_hidden else 0),
        '#define BOARD_OTA_FIRMWARE_URL "{}"'.format(ota_firmware_url),
        "",
        "#define LED_DRIVER_NONE       0",
        "#define LED_DRIVER_PWM_DIRECT 1",
        "#define LED_DRIVER_BUS        2",
        "#define BOARD_LED_DRIVER {}".format(driver_macro),
        "#define BOARD_LED_CONTROL_ENABLED {}".format(1 if led.get("led_control_enabled") else 0),
        "#define BOARD_LED_WHITE_CHANNELS {}".format(white_channels),
        "",
        "// pwm_direct fields - meaningful only when BOARD_LED_DRIVER == LED_DRIVER_PWM_DIRECT",
        "#define BOARD_LED_PWM_BLUE_PIN  {}".format(pwm_direct.get("blue_pin", -1)),
        "#define BOARD_LED_PWM_RED_PIN   {}".format(pwm_direct.get("red_pin", -1)),
        "#define BOARD_LED_PWM_GREEN_PIN {}".format(pwm_direct.get("green_pin", -1)),
        "#define BOARD_LED_PWM_WARM_PIN  {}".format(pwm_direct.get("warm_pin", -1)),
        "#define BOARD_LED_PWM_COLD_PIN  {}".format(pwm_direct.get("cold_pin", -1)),
        "",
        "// bus fields - meaningful only when BOARD_LED_DRIVER == LED_DRIVER_BUS",
        "#define BOARD_LED_BUS_SDA_PIN {}".format(bus.get("sda_pin", -1)),
        "#define BOARD_LED_BUS_SCL_PIN {}".format(bus.get("scl_pin", -1)),
        "// Index (0=red,1=green,2=blue) of which logical channel's value feeds the bus's",
        '// R-slot/G-slot/B-slot - see this board\'s board.json "channel_order" ({}).'.format(channel_order),
        "#define BOARD_LED_BUS_R_SLOT_SOURCE {}".format(r_slot_source),
        "#define BOARD_LED_BUS_G_SLOT_SOURCE {}".format(g_slot_source),
        "#define BOARD_LED_BUS_B_SLOT_SOURCE {}".format(b_slot_source),
        "#define BOARD_LED_BOOT_WHITE_BRIGHTNESS {}".format(bus.get("boot_white_brightness", 0)),
        "",
        "// Fun/spooky LED animations (rainbow/pulse/flicker) - bus driver only",
        "#define BOARD_ANIMATIONS_ENABLED {}".format(1 if animations_enabled else 0),
        "",
    ]
    return "\n".join(lines)


def write_if_changed(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    if os.path.exists(path):
        with open(path) as f:
            if f.read() == content:
                return False
    with open(path, "w") as f:
        f.write(content)
    return True


def run_for_board(firmware_root, board_name):
    repo_root = os.path.dirname(firmware_root)
    cfg = load_board(repo_root, board_name)
    app_cfg = load_app_config(firmware_root)
    header = generate_header(cfg, app_cfg)
    out_path = os.path.join(firmware_root, "include", "generated", "board_config.h")
    changed = write_if_changed(out_path, header)
    print(f"[board_config] {board_name}: wrote {out_path} ({'updated' if changed else 'unchanged'})")

    # Also (re)generate the board's page_index.h from the shared HTML template.
    sys.path.insert(0, os.path.join(firmware_root, "test"))
    import converter  # noqa: E402
    converter.generate_page_index(cfg, firmware_root)
    return cfg


try:
    # PlatformIO/SCons injects Import() as a builtin only when this file is executed via
    # `extra_scripts` - that's a more reliable signal than __file__/argv, since SCons
    # exec()s this file in a globals dict that has neither __file__ nor a real __main__.
    Import("env")  # noqa: F821
    _firmware_root = env["PROJECT_DIR"]  # noqa: F821  - always the dir containing platformio.ini
    run_for_board(_firmware_root, env["PIOENV"])  # noqa: F821
except NameError:
    # Plain `python3 generate_board_config.py <board>` for local inspection/debugging.
    if len(sys.argv) < 2:
        sys.exit("usage: generate_board_config.py <board_name>  (or run via PlatformIO extra_scripts)")
    _firmware_root = os.path.dirname(os.path.abspath(__file__))
    _firmware_root = os.path.dirname(_firmware_root)  # boards/ -> firmware/
    run_for_board(_firmware_root, sys.argv[1])
